### ISSUE TITLE
Update for ForwardDiff v0.6.0

### ISSUE THREAD

**Issue by ranocha** [JuliaDiffEq/DiffEqCallbacks.jl#19]
Due to breaking change in ForwardDiff.jl `v0.6.0`, there have to be some updates, see #18 and https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/200. For `OrdinaryDiffEq.jl`, see also https://github.com/JuliaDiff/ForwardDiff.jl/issues/270.

In short: 
- `REQUIRE`: Use `ForwardDiff 0.6`.
- `manifold.jl`: Replace `DiffBase` with `DiffResult`.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/pull/24 when OrdinaryDiffEq.jl is fixed.
