### ISSUE TITLE
SavingCallback: Interpolation should be in-place

### ISSUE THREAD

**Issue by Gregstrq** [JuliaDiffEq/DiffEqCallbacks.jl#26]
Currently, saving callback uses out of place interpolation, so that each time you want to save data, you need to create the storage for interpolant: [https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/blob/c4afd54d9ec4e914f8606cc7f957f62d454992f7/src/saving.jl#L50](url)

The comment says that it was a conscious decision to prevent force copy later.

But wouldn't it be better to have interpolation in-place?
For example, in this way: [https://github.com/Gregstrq/DiffEqCallbacks.jl/commit/320622bea40f10252088de1c77615212d3cc69af](url)
So the only downside is that you need provide SavingCallback with prototype of u to create storage.

**Comment by ChrisRackauckas** [comment]
At some point in the save there has to be a copy. If you don't copy and you push `u` onto the saving array twice, it will alias and so all of the results will be the same. So you either have to create a new array when interpolating, or you have to interpolate in-place but then `copy` the result before saving it. The latter requires a cache array for the pre-allocated result without a performance advantage. Saving always require allocating, which is why you should minimize it as possible.

**Comment by Gregstrq** [comment]
Is it viable to create cache array once and store it in the SavingCallback; then use ode_interpolant! instead of ode_interpolant?
After we have calculated saving function, we can reuse the same cache array again.

**Comment by ChrisRackauckas** [comment]
But then you have to `copy` it after `ode_interpolant!` anyways: what's gained here?

**Comment by Gregstrq** [comment]
You mean, we need a copy if we want to store u.

I thought that the purpose of SavingCallback was to save only values of some functions, calculated using state vector u, not state vector itself.
For example, for molecular dynamics, save only macroscopic quantities: pressure, tempreture et cetera.

If we want to save u, why do we need SavingCallback, we can calculate everything afterwards?

Sorry, if I misunderstood.

**Comment by ChrisRackauckas** [comment]
I see what you mean, that's a good point. Yes, then in-place makes sense.

**Comment by Gregstrq** [comment]
I guess, I can make a PR then.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/commit/06c0459662f4835e2fc456201d3766ba37b9b0a0

Needed a new thing in the integrator interface to do it well.
