### ISSUE TITLE
Allow users to edit return code when calling `terminate!`

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaDiffEq/DiffEqCallbacks.jl#32]
At the moment the return code is always `:Success` when the solver terminates due to a callback.
But sometimes one would want to handle the solution differently, whether it terminated regularly or by hitting the callback.
Therefore it would be good, if you could pass a custom return code to `terminate!`.

**Comment by BeastyBlacksmith** [comment]
As an update, it is not possible to tweak the return code manually at the moment, because editing before the `terminate!` call will be overridden by `terminate!` and doing it afterwards is not possible.
It would be good to change the default code from `:Success` to something different, like `:Terminated` that would allow distinguishing from reaching the endpoint, but still passing a custom code would be helpful for distinguishing which callback was hit, when using a `CallbackSet`.

**Comment by ChrisRackauckas** [comment]
The solution would be to add a `solution_new_retcode` call in the `terminate!` functions of the solver libraries, and then make the `solve!` routines not change the retcode to `:Success` if they see the `:Terminated` retcode.
