### ISSUE TITLE
Time as a condition in ContinuousCallbacks

### ISSUE THREAD

**Issue by korsbo** [JuliaDiffEq/DiffEqCallbacks.jl#36]
Could we add support for time-based conditions to be properly detected in ContinuousCallbacks? Currently, 

```julia
using DifferentialEquations
using Plots

rn = @reaction_network test begin
    d, x --> 0
end d

u0 = [10.]
p = [1.]
tspan = (0.,10.)

prob = ODEProblem(rn, u0, tspan, p)

condition(u, t, i) = t > 5.
affect!(i) = i.u[1] = 10.
cb = ContinuousCallback(condition, affect!)

sol = solve(prob; callback=cb, dtmax=0.1)

plot(sol)
```

does not do anything at `t=5`.

I know that one can just make it a discrete callback and add some tstops to the solver. This may be more preformant than the propesed continuous callback, but I find it more bulky and less general than I would like.

**Comment by ChrisRackauckas** [comment]
Continuous callbacks work by rootfinding. Make that `t-5` and it should work.

**Comment by korsbo** [comment]
Ahh, silly me. I've been using Continuous callbacks a lot and yet I still managed to confuse myself with this. 
Thanks for your reply!
