### ISSUE TITLE
DtLessThanMin retcode with PositiveDomain although everything is positive

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/DiffEqCallbacks.jl#42]
When I simulate the ODE below with `PositiveDomain` callback, it terminates with `:DtLessThanMin` retcode.  Strangely, if I remove the callback, never hits zero in the example below (but I have other more complicated examples whose solution becomes negative and that's why I wanted to use `PositiveDomain`).

I followed the advice in http://docs.juliadiffeq.org/latest/features/callback_library.html#PositiveDomain-1 and truncate the derivative for non-positive domain.

I better read Shampine et al. and the code, but if you already know the solution or the good place to start, that would be great.

---

The ODE I'm simulating is

$$
  \tau
  \frac{d\boldsymbol{m}}{dt} = - \boldsymbol{m} + \boldsymbol{H} \left(-
  \frac{\sqrt K J \boldsymbol{m} - \boldsymbol{\theta}}{\sqrt{J^{\bullet 2} \boldsymbol{m} + \gamma}}
  \right)
$$

where $H$ is the [Q-function](https://en.wikipedia.org/wiki/Q-function).

Here is the code to reproduce.

```julia
module RNNODE

using DiffEqBase: ODEProblem
using DiffEqCallbacks: PositiveDomain
using Parameters: @unpack, @with_kw

R(x) = erfc(-x / sqrt(2)) / 2

@with_kw struct RNN
    W
    Q
    θ = 1
    τ = 1
    γ = 1e-5

    # Pre-allocated temporary variables:
    x = similar(@view W[:, 1])
    den = similar(@view W[:, 1])
end

function make_rnn(;
        P = 200,
        K = 900,
        seed = 1,
        rng = MersenneTwister(seed),
        kwargs...)
    J = randn(rng, (P, P))
    W = sqrt(K) .* J
    Q = J.^2
    return RNN(; W=W, Q=Q, kwargs...)
end


function f!(du::AbstractVector{Float64}, u, rnn::RNN, t)
    f!(du, u, rnn, t, rnn.x, rnn.den)
end

function f!(du, u, rnn::RNN, t)
    f!(du, u, rnn, t, similar(du), similar(den))
end
# ...for auto-diff

function f!(du, u, rnn::RNN, t, x, den)
    @unpack W, Q, θ, γ, τ = rnn

    m = du  # reuse memory
    @. m = max(0, u)

    # x = W * m - θ = √K J m - θ
    A_mul_B!(x, W, m)
    x .-= θ

    # den = √(J.^2 * m + γ)
    A_mul_B!(den, Q, m)
    @. den = sqrt(den + γ)

    @. du = (- u + R(x / den)) / τ
    @. du = zero_du_if_u_negative(du, u)
end

@inline zero_du_if_u_negative(du, u) = u < 0 ? max(0, du) : du
# http://docs.juliadiffeq.org/latest/features/callback_library.html#PositiveDomain-1


function make_ode(;
        callback = PositiveDomain(abstol=1e-4),
        seed = 1,
        rng = MersenneTwister(seed),
        tspan = (0.0, 10.0),
        kwargs...)

    rnn = make_rnn(; rng=rng, kwargs...)
    u0 = max.(1e-3, randn(rng, size(rnn.W, 1)))

    return ODEProblem(f!, u0, tspan, rnn;
                      callback = callback)
end

end

using DifferentialEquations
ode = RNNODE.make_ode()
# ode = RNNODE.make_ode(callback=nothing)
@time sol = solve(ode)
@assert all(all(u .>= 0) for u in sol.u)
sol.retcode
```

**Comment by tkf** [comment]
BTW, should I post this kind of topic (mostly a usage question) in discourse.julialang.org or somewhere else?

**Comment by tkf** [comment]
Actually I can reproduce a similar behavior with 2-dim ODE. Code: https://gist.github.com/tkf/53fd8a0a19dfeb4729215efb2f40e978

Here is the plot just before the abort due to `:DtLessThanMin`.

![fig](https://user-images.githubusercontent.com/29282/39557170-805d2846-4e3a-11e8-82e7-a0453d736664.png)

Looking at the dense plot "`plot(sol)`" (lines) and the integration result "`plot(sol.t, sol')`" (dots), interpolated solution becomes negative at some point even though the discretized values are not.  Shampine et al. are talking about satisfying the positivity globally and so I guess `PositiveDomain` failed when extrapolation crosses the abstol due to this oscillatory behavior.

In the plot, dots are going up although the derivatives are negative.  So it looks like I'm using inappropriate integrator (here it's the default `AutoTsit5(Rosenbrock23(autodiff=false))`).  Using `Rodas4(autodiff=false)` relaxes the oscillation a little bit (and actually it relaxes to the fixed point before `:DtLessThanMin`) but qualitatively the oscillatory nature doesn't change.

Anyway, I'm closing this issue here since I think it's likely my lack of understanding of integration methods, rather than some problems in `PositiveDomain`.  (But I appreciate any advice!)

**Comment by ChrisRackauckas** [comment]
>Looking at the dense plot "plot(sol)" (lines) and the integration result "plot(sol.t, sol')" (dots), interpolated solution becomes negative at some point even though the discretized values are not. Shampine et al. are talking about satisfying the positivity globally and so I guess PositiveDomain failed when extrapolation crosses the abstol due to this oscillatory behavior.

Yeah, that'll do it. But the oscillation, that's not an interpolation issue right? @YingboMa do we have appropriate tests on the interpolation of `AutoTsit5`?

**Comment by YingboMa** [comment]
No, I don't think we have interpolation tests for `AutoTsit5`.

**Comment by ChrisRackauckas** [comment]
That's probably quite necessary. We should have that as high priority, at least some regression tests. I don't know from the example if it's an AutoTsit5 issue or just the problem, and I'd like to be sure.

**Comment by ChrisRackauckas** [comment]
>The reason why I was mentioning oscillatory behavior is that the solutions stored in sol.u seem to have "no oscillations" in the sense if I linearly interpolate them I won't see the oscillations.

That's indicative of an interpolation problem.

>If I understand correctly, the interpolation respects both u and du/dt, right? That's why I started doubting my usage of the integrator, since the last four points in the above plot go up even though the slopes of the interpolated lines are negative.

They use more values than the `u`s and `du/dt`s, so it's not just possible but expected. See the bouncing ball example with Vern9: the discrete values are constant because it take a step from one event directly to the next, but the interpolation fills in the plot.

>For example, if I enable auto-diff by passing Rodas4() (or Rosenbrock23()), the solution sol.u goes down and du/dt are negative at those points (as I'd expect). My guess is that du/dt is changing so fast at around zero due to the singular nature of the ODE problem I have and the integrator has to know its Jacobian.

Yeah, there's a few things that can be happening here. autodiff could help, stiffness detection could kick in too slow, or maybe it just gets luckier.

**Comment by tkf** [comment]
Thanks a lot!  Using auto-diff for a few dimensional problem is fine but I actually need it for > 1000 dim ODE.  I can implement Jacobian or any other overloads for `f` required for the implicit methods but I wonder if it's going to be fast enough (but let's see).

In my case, some (possibly just a few) components of the ODE may be near the "singular" input (the denominator inside $H$ is near-zero) while others are not.  The issue is that it may be the case that there is such near-singular input almost all the time in some dimensions.  In that case, perhaps it's better to implement it as an split ODE problem and solve it with an IMEX method rather than using composite algorithm?

> They use more values than the us and du/dts, so it's not just possible but expected.

Do you mean integrators evaluates `du/dt` at multiple points or the interpolation does it as well?

But I was just saying that the solution is going to the other direction than the direction naively expected from `du/dt` evaluated at the points in `sol.u`.  (It was also different from the expectation that the zero is the stable fixed point.)  I understood that the sign of the derivative `du/dt(t[i])` of the points in `sol.u` and the direction `sign(sol.u[i+1] - sol.u[i])` it moves _can_ be different since it may have different derivatives between the points.  But I just thought it's rare case and it was not expected.  You wouldn't say that the incompatible sign `any( sign.(get_du(integrator)) .* sign.(integrator.sol.u[end] .- integrator.sol.u[end-1]) .< 0 )` is always expected, right?  (At least it can't be true in explicit Euler)
