### ISSUE TITLE
Saveat with save_positions=(true,true)

### ISSUE THREAD

**Issue by ivborissov** [JuliaDiffEq/DiffEqCallbacks.jl#43]
If a time point is included both in `saveat` and Callback `tstops` with default `save_positions=(true,true)` it is saved 3 times. What is a good solution to have only 2 saved time points in such cases? We can use `save_positions=(false,true)` but then we will loose those `tstops` which are not in `saveat`

**Comment by ChrisRackauckas** [comment]
This should be a DifferentialEquations.jl issue.

**Comment by ivborissov** [comment]
Ok
