### ISSUE TITLE
Switch in callbacks (positive to negative)

### ISSUE THREAD

**Issue by ccontrer** [JuliaDiffEq/DiffEqCallbacks.jl#6]
Regarding switching events, in the [documentation](http://docs.juliadiffeq.org/latest/features/callback_functions.html#Example-2:-Growing-Cell-Population-1) it says
> this function finds events as switching from positive to negative

but this doesn't work at the moment.
Using the bouncing ball example
```
using DifferentialEquations
using ParameterizedFunctions
using Plots

f = @ode_def BallBounce begin
  dy = v
  dv = -g
end g=9.81

function condition(t,u,integrator) # Event when event_f(t,u) == 0
  u[1]
end

function apply_event!(integrator)
  integrator.u[2] = -integrator.u[2]
end

interp_points = 10
rootfind = true
save_positions = (true,true)
cb = ContinuousCallback(condition,apply_event!,rootfind,save_positions)

u0 = [50.0,0.0]
tspan = (0.0,15.0)
prob = ODEProblem(f,u0,tspan) 
sol1 = solve(prob,callback=cb)
plot(sol1)
```
gives
![figure_1](https://cloud.githubusercontent.com/assets/5474403/22077315/e7e9968e-dd70-11e6-9530-819086fcc531.png)
But if we throw the ball upwards 5m from bellow the floor
```
u0 = [-5.0,25.0]
tspan = (0.0,15.0)
prob = ODEProblem(f,u0,tspan) 
sol2 = solve(prob,callback=cb)
plot(sol2)
```
it bounces back when it hits 0 from below
![figure_2](https://cloud.githubusercontent.com/assets/5474403/22077362/21afa19c-dd71-11e6-9099-1e4da999c7ae.png)
We can modify the event to account for the direction, but I have to use the `integrator` to make it work. So, 
```
function condition2(t,u,integrator) # Event when event_f(t,u) == 0
  u[1] > 0 ? integrator.u[1] : 1.
end

cb2 = ContinuousCallback(condition2,apply_event!,rootfind,save_positions)

u0 = [-5.0,35.0]
tspan = (0.0,15.0)
prob = ODEProblem(f,u0,tspan) 
sol3 = solve(prob,callback=cb2)
plot(sol3)
```
gives
![figure_3](https://cloud.githubusercontent.com/assets/5474403/22077423/600c64de-dd71-11e6-848b-15a62f38bba8.png)
which is correct. Would the use of `integrator` affect the interpolation method?

**Comment by ChrisRackauckas** [comment]
>this function finds events as switching from positive to negative

That's an error. The definition of the condition is correct at the top:

http://docs.juliadiffeq.org/latest/features/callback_functions.html#ContinuousCallbacks-1

It always finds roots. The way that you control upcrossings vs downcrossings is that `affect!` is called for an upcrossing and `affect_neg!` is called for a downcrossing (I realize that it's in the constructor, but I forgot to mention this in the extended explanations below!). By default `affect_neg! = affect!`, which means that it will bounce on both upcrossings and downcrossings. But the easy fix should be to pass a function for `affect!` (upcrossings) which does nothing, and have `affect_neg!` be the "bounce" which swaps velocity. You can see that I actually have an integration test which does just that:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/test/ode/ode_event_tests.jl#L53

(though the test doesn't start below zero, which is a good idea).

So can you give this a try? Hopefully it's just a docs problem. If you have time, this is the .md which generates the page of the docs:

https://github.com/JuliaDiffEq/DiffEqDocs.jl/blob/master/docs/src/features/callback_functions.md

**Comment by ccontrer** [comment]
Oh! that makes sense.
I tried the below zero test, but it responds to the upcrossing
```
f = function (t,u,du)
  du[1] = u[2]
  du[2] = -9.81
end

condtion= function (t,u,integrator) # Event when event_f(t,u,k) == 0
  u[1]
end

affect_nothing! = nothing
affect_bounce! = function (integrator)
  integrator.u[2] = -integrator.u[2]
end

interp_points = 10
rootfind = true
save_positions = (true,true)
callback = ContinuousCallback(condtion,affect_nothing!,rootfind,save_positions,affect_neg! = affect_bounce!)

u0 = [-5.0,25.0]
tspan = (0.0,15.0)
prob = ODEProblem(f,u0,tspan)

sol = solve(prob,Tsit5(),callback=callback,adaptive=false,dt=1/4)
plot(sol)
``` 
![figure_4](https://cloud.githubusercontent.com/assets/5474403/22080302/50420e40-dd7c-11e6-90cd-91bbffc8c32a.png)
However, bouncing only upcrossing
```
callback = ContinuousCallback(condtion,affect_bounce!,rootfind,save_positions,affect_neg! = affect_nothing!)

u0 = [50.0,0.0]
```
works as expected with above zero initial conditions.

**Comment by ChrisRackauckas** [comment]
Oh did I flip upcrossing and downcrossing?

**Comment by ccontrer** [comment]
Well, I think the opposite give the same output
```
callback = ContinuousCallback(condtion,affect_bounce!,rootfind,save_positions,affect_neg! = affect_negative!)

```

**Comment by ChrisRackauckas** [comment]
Oh okay, then it sounds like a bug. I'll look into it.

**Comment by ChrisRackauckas** [comment]
Thanks for reporting this. I was able to reproduce it and it's fixed on master.

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/ed89e538f7e588691fe81f1467bf62c1c4d73e58

**Comment by ccontrer** [comment]
Funny, it looks like a previous event affects the flag of the other effect. Runing
```
f = function (t,u,du)
  du[1] = u[2]
  du[2] = -9.81
end

condtion= function (t,u,integrator) # Event when event_f(t,u,k) == 0
  u[1]
end

affect_nothing! = nothing
affect_bounce! = function (integrator)
  integrator.u[2] = -integrator.u[2]
end

interp_points = 10
rootfind = true
save_positions = (true,true)
callback = ContinuousCallback(condtion,affect_nothing!, affect_bounce!,rootfind,interp_points,save_positions,1e-14,0)

u0 = [5.0,30.0]
tspan = (0.0,7.0)
prob = ODEProblem(f,u0,tspan)

sol = solve(prob,callback=callback)
plot(sol)
```
gives
![figure_1](https://cloud.githubusercontent.com/assets/5474403/22171280/99abcae0-df47-11e6-9b1c-1fbc75d32f39.png)
But changing
```
u0 = [-5.0,30.0]
```
never calls `event_bounce!`
![figure_2](https://cloud.githubusercontent.com/assets/5474403/22171295/d1049940-df47-11e6-941e-2ad2052d4449.png)
for example if a include a `print` inside it.
